Metrics/LineLength:
  Max: 120

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'pkg/**/*'
    - 'vendor/**/*'
    - 'coverage/**/*'
    - '.idea/**/*'
    - '*.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/MethodLength:
  Max: 11

Style/MethodMissing:
  Enabled: false